-- ============================================================
-- Suivi Nacelle — migration v3
-- 1. Etat intermediaire « en_cours » sur les interventions
--    (a_faire -> en_cours -> faite).
-- 2. Retour arriere : rouvrir un arret « faite » reactive son
--    lien client (token_actif) — gere par trigger, cote serveur.
-- 3. Journal des changements de statut (qui, quoi, quand).
--
-- Additive et idempotente : re-executable sans risque.
-- A coller dans Supabase > SQL Editor.
-- ============================================================


-- ============================================================
-- 1. STATUT « en_cours »
-- ============================================================
-- La contrainte d'origine (CREATE TABLE) s'appelle
-- interventions_statut_check : on la remplace par la version a
-- trois etats. Drop + add : re-executable.

ALTER TABLE interventions DROP CONSTRAINT IF EXISTS interventions_statut_check;
ALTER TABLE interventions ADD CONSTRAINT interventions_statut_check
  CHECK (statut IN ('a_faire', 'en_cours', 'faite'));


-- ============================================================
-- 2. TRIGGER STATUT (remplace la version v1)
-- ============================================================
-- - passage a « faite »   : horodatage + lien client desactive ;
-- - reouverture (faite -> a_faire ou en_cours) : horodatage efface
--   + lien client REACTIVE ;
-- - a_faire <-> en_cours  : ne touche pas au token.

CREATE OR REPLACE FUNCTION nacelle_intervention_faite()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
BEGIN
  IF NEW.statut = 'faite' AND (OLD.statut IS DISTINCT FROM 'faite') THEN
    NEW.faite_at    := COALESCE(NEW.faite_at, NOW());
    NEW.token_actif := FALSE;
  ELSIF OLD.statut = 'faite' AND NEW.statut IN ('a_faire', 'en_cours') THEN
    NEW.faite_at    := NULL;
    NEW.token_actif := TRUE;
  END IF;
  RETURN NEW;
END; $fn$;

-- (le trigger trg_intervention_faite de la v1 pointe deja sur cette
--  fonction : pas besoin de le recreer)


-- ============================================================
-- 3. JOURNAL DES CHANGEMENTS DE STATUT
-- ============================================================

CREATE TABLE IF NOT EXISTS interventions_journal (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intervention_id UUID NOT NULL REFERENCES interventions(id) ON DELETE CASCADE,
  ancien_statut   TEXT,
  nouveau_statut  TEXT NOT NULL,
  token_reactive  BOOLEAN NOT NULL DEFAULT FALSE,   -- lien client re-ouvert par ce changement
  modifie_par     UUID,                             -- auth.uid() (NULL si service_role)
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_journal_intervention
  ON interventions_journal (intervention_id, created_at DESC);

-- Ecriture UNIQUEMENT par trigger (SECURITY DEFINER : passe la RLS).
CREATE OR REPLACE FUNCTION nacelle_journal_statut()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
BEGIN
  IF NEW.statut IS DISTINCT FROM OLD.statut THEN
    INSERT INTO interventions_journal
      (intervention_id, ancien_statut, nouveau_statut, token_reactive, modifie_par)
    VALUES
      (NEW.id, OLD.statut, NEW.statut,
       (NEW.token_actif AND NOT OLD.token_actif), auth.uid());
  END IF;
  RETURN NEW;
END; $fn$;

DROP TRIGGER IF EXISTS trg_journal_statut ON interventions;
CREATE TRIGGER trg_journal_statut
  AFTER UPDATE ON interventions
  FOR EACH ROW EXECUTE FUNCTION nacelle_journal_statut();

-- Lecture : proprietaire de la tournee ou admin. Aucune politique
-- d'ecriture : seul le trigger ecrit.
ALTER TABLE interventions_journal ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS journal_select ON interventions_journal;
CREATE POLICY journal_select ON interventions_journal FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM interventions i
    WHERE i.id = intervention_id
      AND (tournee_est_a_moi(i.tournee_id) OR est_admin())
  ));
