-- ============================================================
-- Suivi Nacelle — migration v1
-- Cible : projet Supabase DEDIE « suivi-nacelle » (ne pas executer
-- sur un autre projet). A coller dans Supabase > SQL Editor.
--
-- Additive et idempotente : ce fichier peut etre re-execute autant
-- de fois que necessaire, il ne detruit aucune donnee.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid(), gen_random_bytes()


-- ============================================================
-- 1. TABLES
-- ============================================================

-- --- profils : extension de auth.users -----------------------
CREATE TABLE IF NOT EXISTS profils (
  id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nom        TEXT NOT NULL DEFAULT '',
  role       TEXT NOT NULL DEFAULT 'nacelliste'
             CHECK (role IN ('admin', 'nacelliste')),
  login      TEXT,
  actif      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE profils ADD COLUMN IF NOT EXISTS nom   TEXT NOT NULL DEFAULT '';
ALTER TABLE profils ADD COLUMN IF NOT EXISTS login TEXT;
ALTER TABLE profils ADD COLUMN IF NOT EXISTS actif BOOLEAN NOT NULL DEFAULT TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_profils_login
  ON profils (LOWER(login)) WHERE login IS NOT NULL;


-- --- tournees ------------------------------------------------
CREATE TABLE IF NOT EXISTS tournees (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nacelliste_id UUID NOT NULL REFERENCES profils(id) ON DELETE CASCADE,
  date          DATE NOT NULL DEFAULT ((NOW() AT TIME ZONE 'Europe/Paris')::DATE),
  statut        TEXT NOT NULL DEFAULT 'preparee'
                CHECK (statut IN ('preparee', 'en_cours', 'terminee')),
  demarree_at   TIMESTAMPTZ,
  terminee_at   TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Une seule tournee par nacelliste et par jour : l'application peut
-- faire « ma tournee du jour » sans ambiguite.
CREATE UNIQUE INDEX IF NOT EXISTS idx_tournees_jour ON tournees (nacelliste_id, date);
CREATE INDEX IF NOT EXISTS idx_tournees_date   ON tournees (date);
CREATE INDEX IF NOT EXISTS idx_tournees_statut ON tournees (statut);


-- --- interventions -------------------------------------------
-- Le token est genere PAR LA BASE (48 caracteres hexadecimaux issus
-- de 24 octets aleatoires cryptographiques) : imprevisible, jamais
-- choisi par le client.
CREATE TABLE IF NOT EXISTS interventions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tournee_id  UUID NOT NULL REFERENCES tournees(id) ON DELETE CASCADE,
  ordre       INT  NOT NULL DEFAULT 0,          -- position dans la tournee optimisee (1..N)
  client_nom  TEXT,                             -- optionnel
  adresse     TEXT NOT NULL DEFAULT '',
  lat         DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN  -90 AND  90),
  lng         DOUBLE PRECISION NOT NULL CHECK (lng BETWEEN -180 AND 180),
  statut      TEXT NOT NULL DEFAULT 'a_faire' CHECK (statut IN ('a_faire', 'faite')),
  faite_at    TIMESTAMPTZ,
  token       TEXT NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(24), 'hex'),
  token_actif BOOLEAN NOT NULL DEFAULT TRUE,
  eta         TIMESTAMPTZ,                      -- heure d'arrivee estimee
  infos_avant TEXT,                             -- montre au client AVANT l'intervention
  infos_apres TEXT,                             -- montre au client APRES (« termine »)
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE interventions ADD COLUMN IF NOT EXISTS client_nom  TEXT;
ALTER TABLE interventions ADD COLUMN IF NOT EXISTS eta         TIMESTAMPTZ;
ALTER TABLE interventions ADD COLUMN IF NOT EXISTS infos_avant TEXT;
ALTER TABLE interventions ADD COLUMN IF NOT EXISTS infos_apres TEXT;

CREATE INDEX IF NOT EXISTS idx_interventions_tournee ON interventions (tournee_id, ordre);


-- --- positions : trace GPS live ------------------------------
-- On ne garde que l'utile : la DERNIERE position par tournee fait
-- foi ; nettoyer_positions() purge le reste (voir plus bas).
CREATE TABLE IF NOT EXISTS positions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nacelliste_id UUID NOT NULL REFERENCES profils(id)  ON DELETE CASCADE,
  tournee_id    UUID NOT NULL REFERENCES tournees(id) ON DELETE CASCADE,
  lat           DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN  -90 AND  90),
  lng           DOUBLE PRECISION NOT NULL CHECK (lng BETWEEN -180 AND 180),
  captured_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_positions_tournee
  ON positions (tournee_id, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_positions_nacelliste
  ON positions (nacelliste_id, captured_at DESC);


-- --- parametres : ligne unique de reglages -------------------
CREATE TABLE IF NOT EXISTS parametres (
  id                     INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  temps_intervention_min INT  NOT NULL DEFAULT 20,   -- duree moyenne chez un client (ETA)
  seuil_retard_min       INT  NOT NULL DEFAULT 15,   -- ETA depassee de X min -> afficher le numero
  telephone_contact      TEXT NOT NULL DEFAULT '0615324767',
  infos_avant_defaut     TEXT NOT NULL DEFAULT 'Le nacelliste passe finaliser le raccordement de votre ligne fibre. Merci de laisser l''accès à la façade dégagé.',
  infos_apres_defaut     TEXT NOT NULL DEFAULT 'Intervention terminée. Votre ligne fibre est finalisée.',
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO parametres (id) VALUES (1) ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- 2. HELPERS DE SECURITE (SECURITY DEFINER : ne rebouclent pas sur la RLS)
-- ============================================================

CREATE OR REPLACE FUNCTION est_admin() RETURNS BOOLEAN
LANGUAGE SQL SECURITY DEFINER STABLE SET search_path = public AS $fn$
  SELECT EXISTS (
    SELECT 1 FROM profils WHERE id = auth.uid() AND actif AND role = 'admin'
  )
$fn$;

-- La tournee appartient-elle a l'utilisateur connecte ?
-- Utilisee par les politiques d'« interventions » et de « positions »
-- pour eviter une sous-requete qui repasserait par la RLS de tournees.
CREATE OR REPLACE FUNCTION tournee_est_a_moi(p_tournee UUID) RETURNS BOOLEAN
LANGUAGE SQL SECURITY DEFINER STABLE SET search_path = public AS $fn$
  SELECT EXISTS (
    SELECT 1 FROM tournees WHERE id = p_tournee AND nacelliste_id = auth.uid()
  )
$fn$;


-- ============================================================
-- 3. TRIGGERS
-- ============================================================

-- Profil cree automatiquement a la creation d'un compte Auth.
-- L'admin passe par l'Edge Function « admin-comptes », qui renseigne
-- ces metadonnees.
CREATE OR REPLACE FUNCTION nacelle_handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
BEGIN
  INSERT INTO profils (id, nom, role, login)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nom', ''),
    COALESCE(NEW.raw_user_meta_data->>'role', 'nacelliste'),
    NULLIF(NEW.raw_user_meta_data->>'login', '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END; $fn$;

DROP TRIGGER IF EXISTS trg_on_auth_user_created ON auth.users;
CREATE TRIGGER trg_on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION nacelle_handle_new_user();

-- Passage en « faite » : horodatage + desactivation du lien client,
-- toujours cote serveur (le client ne peut pas l'oublier ni tricher).
CREATE OR REPLACE FUNCTION nacelle_intervention_faite()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
BEGIN
  IF NEW.statut = 'faite' AND (OLD.statut IS DISTINCT FROM 'faite') THEN
    NEW.faite_at    := COALESCE(NEW.faite_at, NOW());
    NEW.token_actif := FALSE;
  ELSIF NEW.statut = 'a_faire' AND OLD.statut = 'faite' THEN
    NEW.faite_at    := NULL;
    NEW.token_actif := TRUE;
  END IF;
  RETURN NEW;
END; $fn$;

DROP TRIGGER IF EXISTS trg_intervention_faite ON interventions;
CREATE TRIGGER trg_intervention_faite
  BEFORE UPDATE ON interventions
  FOR EACH ROW EXECUTE FUNCTION nacelle_intervention_faite();

-- Changement de statut d'une tournee : horodatages automatiques, et
-- EXPIRATION de tous les liens clients quand la tournee est terminee.
CREATE OR REPLACE FUNCTION nacelle_tournee_statut()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
BEGIN
  IF NEW.statut = 'en_cours' AND OLD.statut = 'preparee' THEN
    NEW.demarree_at := COALESCE(NEW.demarree_at, NOW());
  ELSIF NEW.statut = 'terminee' AND (OLD.statut IS DISTINCT FROM 'terminee') THEN
    NEW.terminee_at := COALESCE(NEW.terminee_at, NOW());
  END IF;
  RETURN NEW;
END; $fn$;

DROP TRIGGER IF EXISTS trg_tournee_statut ON tournees;
CREATE TRIGGER trg_tournee_statut
  BEFORE UPDATE ON tournees
  FOR EACH ROW EXECUTE FUNCTION nacelle_tournee_statut();

-- La desactivation des tokens se fait APRES l'update (il faut que la
-- ligne tournee soit deja a jour).
CREATE OR REPLACE FUNCTION nacelle_tournee_expire_tokens()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
BEGIN
  IF NEW.statut = 'terminee' AND (OLD.statut IS DISTINCT FROM 'terminee') THEN
    UPDATE interventions SET token_actif = FALSE WHERE tournee_id = NEW.id;
  END IF;
  RETURN NEW;
END; $fn$;

DROP TRIGGER IF EXISTS trg_tournee_expire_tokens ON tournees;
CREATE TRIGGER trg_tournee_expire_tokens
  AFTER UPDATE ON tournees
  FOR EACH ROW EXECUTE FUNCTION nacelle_tournee_expire_tokens();


-- ============================================================
-- 4. PURGE DES POSITIONS
-- ============================================================
-- La trace GPS n'a pas vocation a etre conservee : on garde 48 h
-- (de quoi couvrir la journee en cours), le reste est supprime.
-- Appelee par l'application au demarrage d'une tournee.

CREATE OR REPLACE FUNCTION nettoyer_positions() RETURNS INT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE v_n INT;
BEGIN
  DELETE FROM positions WHERE captured_at < NOW() - INTERVAL '48 hours';
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END; $fn$;

REVOKE ALL     ON FUNCTION nettoyer_positions() FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION nettoyer_positions() TO authenticated;


-- ============================================================
-- 5. REALTIME
-- ============================================================
-- Publie les changements de « positions » et « interventions » aux
-- abonnes AUTORISES par la RLS (admin, nacelliste proprietaire).
-- La page client, elle, n'a pas de compte : elle interroge l'Edge
-- Function « suivi-client » (voir README), la RLS ne s'applique donc
-- jamais a elle et rien n'est publie aux anonymes.

DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE positions;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE interventions;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE tournees;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ============================================================
-- 6. ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE profils       ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournees      ENABLE ROW LEVEL SECURITY;
ALTER TABLE interventions ENABLE ROW LEVEL SECURITY;
ALTER TABLE positions     ENABLE ROW LEVEL SECURITY;
ALTER TABLE parametres    ENABLE ROW LEVEL SECURITY;

-- --- profils -------------------------------------------------
-- Chacun se voit ; l'admin voit tout et est SEUL a ecrire.
DROP POLICY IF EXISTS profils_select ON profils;
CREATE POLICY profils_select ON profils FOR SELECT TO authenticated
  USING (id = auth.uid() OR est_admin());

DROP POLICY IF EXISTS profils_insert ON profils;
CREATE POLICY profils_insert ON profils FOR INSERT TO authenticated
  WITH CHECK (est_admin());

DROP POLICY IF EXISTS profils_update ON profils;
CREATE POLICY profils_update ON profils FOR UPDATE TO authenticated
  USING (est_admin()) WITH CHECK (est_admin());

DROP POLICY IF EXISTS profils_delete ON profils;
CREATE POLICY profils_delete ON profils FOR DELETE TO authenticated
  USING (est_admin());

-- --- tournees ------------------------------------------------
-- Le nacelliste ne voit et ne gere que SES tournees ; l'admin tout.
DROP POLICY IF EXISTS tournees_select ON tournees;
CREATE POLICY tournees_select ON tournees FOR SELECT TO authenticated
  USING (nacelliste_id = auth.uid() OR est_admin());

DROP POLICY IF EXISTS tournees_insert ON tournees;
CREATE POLICY tournees_insert ON tournees FOR INSERT TO authenticated
  WITH CHECK (nacelliste_id = auth.uid() OR est_admin());

DROP POLICY IF EXISTS tournees_update ON tournees;
CREATE POLICY tournees_update ON tournees FOR UPDATE TO authenticated
  USING (nacelliste_id = auth.uid() OR est_admin())
  WITH CHECK (nacelliste_id = auth.uid() OR est_admin());

DROP POLICY IF EXISTS tournees_delete ON tournees;
CREATE POLICY tournees_delete ON tournees FOR DELETE TO authenticated
  USING (nacelliste_id = auth.uid() OR est_admin());

-- --- interventions -------------------------------------------
-- Visibles/modifiables uniquement via la propriete de la tournee.
DROP POLICY IF EXISTS interventions_select ON interventions;
CREATE POLICY interventions_select ON interventions FOR SELECT TO authenticated
  USING (tournee_est_a_moi(tournee_id) OR est_admin());

DROP POLICY IF EXISTS interventions_insert ON interventions;
CREATE POLICY interventions_insert ON interventions FOR INSERT TO authenticated
  WITH CHECK (tournee_est_a_moi(tournee_id) OR est_admin());

DROP POLICY IF EXISTS interventions_update ON interventions;
CREATE POLICY interventions_update ON interventions FOR UPDATE TO authenticated
  USING (tournee_est_a_moi(tournee_id) OR est_admin())
  WITH CHECK (tournee_est_a_moi(tournee_id) OR est_admin());

DROP POLICY IF EXISTS interventions_delete ON interventions;
CREATE POLICY interventions_delete ON interventions FOR DELETE TO authenticated
  USING (tournee_est_a_moi(tournee_id) OR est_admin());

-- --- positions -----------------------------------------------
-- ECRITURE : uniquement le nacelliste proprietaire, sur SA tournee,
-- et en son propre nom (nacelliste_id impose = auth.uid()).
DROP POLICY IF EXISTS positions_select ON positions;
CREATE POLICY positions_select ON positions FOR SELECT TO authenticated
  USING (nacelliste_id = auth.uid() OR est_admin());

DROP POLICY IF EXISTS positions_insert ON positions;
CREATE POLICY positions_insert ON positions FOR INSERT TO authenticated
  WITH CHECK (nacelliste_id = auth.uid() AND tournee_est_a_moi(tournee_id));

DROP POLICY IF EXISTS positions_delete ON positions;
CREATE POLICY positions_delete ON positions FOR DELETE TO authenticated
  USING (nacelliste_id = auth.uid() OR est_admin());
-- (pas d'UPDATE : une position ne se modifie pas, elle se remplace)

-- --- parametres ----------------------------------------------
-- Lisibles par tous les connectes (le nacelliste a besoin du temps
-- d'intervention et des textes par defaut) ; modifiables par l'admin.
DROP POLICY IF EXISTS parametres_select ON parametres;
CREATE POLICY parametres_select ON parametres FOR SELECT TO authenticated
  USING (TRUE);

DROP POLICY IF EXISTS parametres_update ON parametres;
CREATE POLICY parametres_update ON parametres FOR UPDATE TO authenticated
  USING (est_admin()) WITH CHECK (est_admin());

DROP POLICY IF EXISTS parametres_insert ON parametres;
CREATE POLICY parametres_insert ON parametres FOR INSERT TO authenticated
  WITH CHECK (est_admin());


-- ============================================================
-- 7. AMORCAGE — creer le compte admin
-- ============================================================
-- 1. Supabase > Authentication > Users > « Add user » :
--       Email    : admin@nacelle.local   (identifiant de connexion : « admin »)
--       Password : celui de votre choix
--       [x] Auto Confirm User
-- 2. Puis executer ici, une seule fois :
--
--    UPDATE profils
--       SET nom = 'Admin', role = 'admin', login = 'admin'
--     WHERE id = (SELECT id FROM auth.users WHERE email = 'admin@nacelle.local');
--
-- Les comptes nacellistes (Hamda, Lheoui, Klach, Zitouni) se creent
-- ensuite depuis l'ecran « Comptes » de l'application.
